num1 = int(input("please enter the number: "))
num2 = int(input("please enter the number: "))
print (num1 + num2)
print (num1 - num2)
print (num1 / num2)
print (num1 * num2)
print (num1 > num2)
print (num1<num2)
print (num1>=num2)
print(num1>=num2)